import type { OperationModel } from '../../models/operation';
import { toTypeName } from '../../utils/naming';
import {
  operationArgsTypeName,
  pickPrimaryResponseStatus,
  responseTypeName,
} from '../../utils/typeNames';

export class ReactQueryGenerator {
  generateModule(operations: OperationModel[]): string {
    const lines: string[] = [];

    lines.push('// Generated by Swagger to SDK.');
    lines.push(
      "import { mutationOptions, queryOptions, useMutation, useQuery, type UseMutationOptions, type UseQueryOptions } from '@tanstack/react-query';"
    );
    lines.push("import type * as Types from './types';");
    lines.push("import * as Client from './client';");
    lines.push('');

    for (const operation of operations) {
      lines.push(this.generateOperationBlock(operation));
      lines.push('');
    }

    return `${lines.join('\n').trim()}\n`;
  }

  private generateOperationBlock(operation: OperationModel): string {
    return operation.method === 'get'
      ? this.generateQueryOperationBlock(operation)
      : this.generateMutationOperationBlock(operation);
  }

  private generateQueryOperationBlock(operation: OperationModel): string {
    const responseType = this.getResponseType(operation);
    const argsType = `Types.${operationArgsTypeName(operation.functionName)}`;
    const queryKeyName = `${operation.functionName}QueryKey`;
    const queryOptionsName = `${operation.functionName}QueryOptions`;
    const hookName = `use${toTypeName(operation.functionName)}`;
    const hasRequiredArgs = this.hasRequiredArgs(operation);
    const argsSignature = hasRequiredArgs ? `args: ${argsType}` : `args: ${argsType} = {}`;
    const argsPassThrough = hasRequiredArgs ? 'args' : 'args = {}';

    return `export function ${queryKeyName}(${argsSignature}) {
  return [${JSON.stringify(operation.functionName)}, args] as const;
}

export function ${queryOptionsName}(
  ${argsSignature},
  options?: Omit<
    UseQueryOptions<
      ${responseType},
      Error,
      ${responseType},
      ReturnType<typeof ${queryKeyName}>
    >,
    'queryKey' | 'queryFn'
  >
) {
  return queryOptions({
    ...options,
    queryKey: ${queryKeyName}(${argsPassThrough}),
    queryFn: () => Client.${operation.functionName}(args),
  });
}

export function ${hookName}(
  ${argsSignature},
  options?: Omit<
    UseQueryOptions<
      ${responseType},
      Error,
      ${responseType},
      ReturnType<typeof ${queryKeyName}>
    >,
    'queryKey' | 'queryFn'
  >
) {
  return useQuery(${queryOptionsName}(${argsPassThrough}, options));
}`;
  }

  private generateMutationOperationBlock(operation: OperationModel): string {
    const responseType = this.getResponseType(operation);
    const argsType = `Types.${operationArgsTypeName(operation.functionName)}`;
    const mutationKeyName = `${operation.functionName}MutationKey`;
    const mutationOptionsName = `${operation.functionName}MutationOptions`;
    const hookName = `use${toTypeName(operation.functionName)}Mutation`;

    return `export function ${mutationKeyName}() {
  return [${JSON.stringify(operation.functionName)}] as const;
}

export function ${mutationOptionsName}(
  options?: Omit<
    UseMutationOptions<${responseType}, Error, ${argsType}>,
    'mutationKey' | 'mutationFn'
  >
) {
  return mutationOptions({
    ...options,
    mutationKey: ${mutationKeyName}(),
    mutationFn: (args: ${argsType}) => Client.${operation.functionName}(args),
  });
}

export function ${hookName}(
  options?: Omit<
    UseMutationOptions<${responseType}, Error, ${argsType}>,
    'mutationKey' | 'mutationFn'
  >
) {
  return useMutation(${mutationOptionsName}(options));
}`;
  }

  private getResponseType(operation: OperationModel): string {
    const statusCode = pickPrimaryResponseStatus(operation.responses) ?? '200';
    return `Types.${responseTypeName(operation.functionName, statusCode)}`;
  }

  private hasRequiredArgs(operation: OperationModel): boolean {
    const hasRequiredPath = operation.parameters.some(
      (parameter) => parameter.in === 'path' && parameter.required
    );
    const hasRequiredBody = operation.requestBody?.required === true;

    return hasRequiredPath || hasRequiredBody;
  }
}
