import type { Config } from '../../models/config';
import type { OperationModel } from '../../models/operation';
import {
  cookieParamsTypeName,
  headerParamsTypeName,
  operationArgsTypeName,
  pathParamsTypeName,
  pickPrimaryResponseStatus,
  queryParamsTypeName,
  requestBodyTypeName,
  responseTypeName,
} from '../../utils/typeNames';

export class SDKGenerator {
  constructor(private readonly configuration: Config) {}

  generateTransport(): string {
    if (this.usesAxiosTransport()) {
      return this.generateAxiosTransport();
    }

    return this.generateFetchTransport();
  }

  generateMethods(operations: OperationModel[]): string {
    const lines: string[] = [];

    lines.push('// Generated by Swagger to SDK.');
    lines.push("import type * as Types from './types';");
    lines.push("import { createTransport } from './transport';");
    lines.push('');

    if (this.configuration.baseURL) {
      lines.push(`const BASE_URL = ${JSON.stringify(this.configuration.baseURL)};`);
    } else {
      lines.push('const BASE_URL: string | undefined = undefined;');
    }

    lines.push('');
    lines.push('const transport = createTransport();');
    lines.push('');
    lines.push(this.generateBuildUrlHelper());
    lines.push('');

    for (const operation of operations) {
      lines.push(this.generateMethod(operation));
      lines.push('');
    }

    return `${lines.join('\n').trim()}\n`;
  }

  private generateMethod(operation: OperationModel): string {
    const uppercaseMethod = operation.method.toUpperCase();
    const statusCode = pickPrimaryResponseStatus(operation.responses) ?? '200';
    const responseType = `Types.${responseTypeName(operation.functionName, statusCode)}`;

    const hasPathParams = operation.parameters.some((parameter) => parameter.in === 'path');
    const hasQueryParams = operation.parameters.some((parameter) => parameter.in === 'query');
    const hasHeaderParams = operation.parameters.some((parameter) => parameter.in === 'header');
    const hasCookieParams = operation.parameters.some((parameter) => parameter.in === 'cookie');
    const requestBody = operation.requestBody?.content['application/json'];
    const hasBody = Boolean(requestBody);
    const bodyRequired = operation.requestBody?.required === true;

    const hasRequiredArgs = hasPathParams || bodyRequired;
    const argsType = `Types.${operationArgsTypeName(operation.functionName)}`;
    const argsSignature = hasRequiredArgs ? `args: ${argsType}` : `args: ${argsType} = {}`;

    return `export async function ${operation.functionName}(${argsSignature}): Promise<${responseType}> {
  const url = buildUrl(
    ${JSON.stringify(operation.path)},
    ${
      hasPathParams
        ? '(args.path as unknown as Record<string, string | number | boolean>)'
        : 'undefined'
    },
    ${hasQueryParams ? '(args.query as unknown as Record<string, unknown> | undefined)' : 'undefined'},
    BASE_URL
  );

  return transport.request<${responseType}>({
    method: ${JSON.stringify(uppercaseMethod)},
    url,
    headers: {
      ...(args.headers ?? {}),
      ${hasHeaderParams ? '...(args.headerParams ?? {}),' : ''}
      ${hasBody ? "'Content-Type': 'application/json'," : ''}
    },
    ${hasBody ? 'body: args.body,' : 'body: undefined,'}
  });
}`;
  }

  private generateBuildUrlHelper(): string {
    return `function buildUrl(
  pathTemplate: string,
  pathParams?: Record<string, string | number | boolean>,
  query?: Record<string, unknown>,
  baseURL?: string
): string {
  const replacedPath = pathTemplate.replace(/\\{([^}]+)\\}/g, (_, key: string) => {
    if (!pathParams || pathParams[key] === undefined) {
      throw new Error(\`Missing path parameter: \${key}\`);
    }

    return encodeURIComponent(String(pathParams[key]));
  });

  const searchParams = new URLSearchParams();

  if (query) {
    for (const [key, value] of Object.entries(query)) {
      if (value === undefined || value === null) {
        continue;
      }

      if (Array.isArray(value)) {
        for (const item of value) {
          searchParams.append(key, String(item));
        }
        continue;
      }

      searchParams.append(key, String(value));
    }
  }

  const queryString = searchParams.toString();
  const normalizedPath = replacedPath.startsWith('/') ? replacedPath : \`/\${replacedPath}\`;

  if (!baseURL) {
    return queryString ? \`\${normalizedPath}?\${queryString}\` : normalizedPath;
  }

  const normalizedBase = baseURL.replace(/\\/+$/, '');
  return queryString
    ? \`\${normalizedBase}\${normalizedPath}?\${queryString}\`
    : \`\${normalizedBase}\${normalizedPath}\`;
}`;
  }

  private generateFetchTransport(): string {
    return `// Generated by Swagger to SDK.
export interface TransportRequestOptions {
  method: string;
  url: string;
  headers?: Record<string, string>;
  body?: unknown;
}

export interface Transport {
  request<TResponse>(options: TransportRequestOptions): Promise<TResponse>;
}

export function createTransport(): Transport {
  return {
    async request<TResponse>({ method, url, headers, body }: TransportRequestOptions): Promise<TResponse> {
      const response = await fetch(url, {
        method,
        headers,
        body: body !== undefined ? JSON.stringify(body) : undefined,
      });

      if (!response.ok) {
        throw new Error('Request failed with status ' + response.status);
      }

      if (response.status === 204) {
        return undefined as TResponse;
      }

      return (await response.json()) as TResponse;
    },
  };
}`;
  }

  private generateAxiosTransport(): string {
    return `// Generated by Swagger to SDK.
import axios from 'axios';

export interface TransportRequestOptions {
  method: string;
  url: string;
  headers?: Record<string, string>;
  body?: unknown;
}

export interface Transport {
  request<TResponse>(options: TransportRequestOptions): Promise<TResponse>;
}

export function createTransport(): Transport {
  return {
    async request<TResponse>({ method, url, headers, body }: TransportRequestOptions): Promise<TResponse> {
      const response = await axios.request<TResponse>({
        method,
        url,
        headers,
        data: body,
        validateStatus: () => true,
      });

      if (response.status < 200 || response.status >= 300) {
        throw new Error('Request failed with status ' + response.status);
      }

      if (response.status === 204) {
        return undefined as TResponse;
      }

      return response.data;
    },
  };
}`;
  }

  private usesAxiosTransport(): boolean {
    return this.configuration.adapter === 'axios';
  }
}
