import type { Config } from '../../models/config';
import type { OperationModel } from '../../models/operation';
import {
  cookieParamsTypeName,
  headerParamsTypeName,
  pathParamsTypeName,
  pickPrimaryResponseStatus,
  queryParamsTypeName,
  requestBodyTypeName,
  responseTypeName,
} from '../../utils/typeNames';

export class SDKGenerator {
  constructor(private readonly configuration: Config) {}

  generateMethods(operations: OperationModel[]): string {
    const lines: string[] = [];

    lines.push('// Generated by PLF ES Extension.');
    lines.push("import type * as Types from './types';");
    lines.push('');

    if (this.configuration.baseURL) {
      lines.push(`const BASE_URL = ${JSON.stringify(this.configuration.baseURL)};`);
    } else {
      lines.push('const BASE_URL: string | undefined = undefined;');
    }

    lines.push('');
    lines.push(this.generateBuildUrlHelper());
    lines.push('');

    for (const operation of operations) {
      lines.push(this.generateMethod(operation));
      lines.push('');
    }

    return `${lines.join('\n').trim()}\n`;
  }

  private generateMethod(operation: OperationModel): string {
    const uppercaseMethod = operation.method.toUpperCase();
    const statusCode = pickPrimaryResponseStatus(operation.responses) ?? '200';
    const responseType = `Types.${responseTypeName(operation.functionName, statusCode)}`;

    const hasPathParams = operation.parameters.some((parameter) => parameter.in === 'path');
    const hasQueryParams = operation.parameters.some((parameter) => parameter.in === 'query');
    const hasHeaderParams = operation.parameters.some((parameter) => parameter.in === 'header');
    const hasCookieParams = operation.parameters.some((parameter) => parameter.in === 'cookie');
    const requestBody = operation.requestBody?.content['application/json'];
    const hasBody = Boolean(requestBody);
    const bodyRequired = operation.requestBody?.required === true;

    const argsFields: string[] = [];

    if (hasPathParams) {
      argsFields.push(`path: Types.${pathParamsTypeName(operation.functionName)};`);
    }

    if (hasQueryParams) {
      argsFields.push(`query?: Types.${queryParamsTypeName(operation.functionName)};`);
    }

    if (hasHeaderParams) {
      argsFields.push(`headerParams?: Types.${headerParamsTypeName(operation.functionName)};`);
    }

    if (hasCookieParams) {
      argsFields.push(`cookieParams?: Types.${cookieParamsTypeName(operation.functionName)};`);
    }

    if (hasBody) {
      argsFields.push(
        `body${bodyRequired ? '' : '?'}: Types.${requestBodyTypeName(operation.functionName)};`
      );
    }

    argsFields.push('headers?: Record<string, string>;');

    const hasRequiredArgs = hasPathParams || bodyRequired;
    const argsType = `{
${argsFields.map((field) => `  ${field}`).join('\n')}
}`;
    const argsSignature = hasRequiredArgs ? `args: ${argsType}` : `args: ${argsType} = {}`;

    const jsonHandling = hasBody
      ? `
    ...(args.body !== undefined ? { 'Content-Type': 'application/json' } : {}),`
      : '';

    const bodyHandling = hasBody
      ? "\n    body: args.body !== undefined ? JSON.stringify(args.body) : undefined,"
      : '';
    const headerParamsSpread = hasHeaderParams ? "\n      ...(args.headerParams ?? {})," : '';

    const responseHandling = statusCode === '204'
      ? '  return undefined as Types.' + responseTypeName(operation.functionName, statusCode) + ';'
      : `  return (await response.json()) as ${responseType};`;

    return `export async function ${operation.functionName}(${argsSignature}): Promise<${responseType}> {
  const url = buildUrl(
    ${JSON.stringify(operation.path)},
    ${
      hasPathParams
        ? '(args.path as unknown as Record<string, string | number | boolean>)'
        : 'undefined'
    },
    ${hasQueryParams ? '(args.query as unknown as Record<string, unknown> | undefined)' : 'undefined'},
    BASE_URL
  );

  const response = await fetch(url, {
    method: ${JSON.stringify(uppercaseMethod)},
    headers: {
      ...(args.headers ?? {}),${headerParamsSpread}${jsonHandling}
    },${bodyHandling}
  });

  if (!response.ok) {
    throw new Error('Request failed with status ' + response.status);
  }

${responseHandling}
}`;
  }

  private generateBuildUrlHelper(): string {
    return `function buildUrl(
  pathTemplate: string,
  pathParams?: Record<string, string | number | boolean>,
  query?: Record<string, unknown>,
  baseURL?: string
): string {
  const replacedPath = pathTemplate.replace(/\\{([^}]+)\\}/g, (_, key: string) => {
    if (!pathParams || pathParams[key] === undefined) {
      throw new Error(\`Missing path parameter: \${key}\`);
    }

    return encodeURIComponent(String(pathParams[key]));
  });

  const searchParams = new URLSearchParams();

  if (query) {
    for (const [key, value] of Object.entries(query)) {
      if (value === undefined || value === null) {
        continue;
      }

      if (Array.isArray(value)) {
        for (const item of value) {
          searchParams.append(key, String(item));
        }
        continue;
      }

      searchParams.append(key, String(value));
    }
  }

  const queryString = searchParams.toString();
  const normalizedPath = replacedPath.startsWith('/') ? replacedPath : \`/\${replacedPath}\`;

  if (!baseURL) {
    return queryString ? \`\${normalizedPath}?\${queryString}\` : normalizedPath;
  }

  const normalizedBase = baseURL.replace(/\\/+$/, '');
  return queryString
    ? \`\${normalizedBase}\${normalizedPath}?\${queryString}\`
    : \`\${normalizedBase}\${normalizedPath}\`;
}`;
  }
}
