import type {
  OperationModel,
  OperationResponseModel,
  ParameterModel,
} from '../../models/operation';
import type { SchemaModel, SchemaRefOrInline } from '../../models/schema';
import { toTypeName } from '../../utils/naming';
import {
  cookieParamsTypeName,
  headerParamsTypeName,
  operationArgsTypeName,
  pathParamsTypeName,
  pickPrimaryResponseStatus,
  queryParamsTypeName,
  requestBodyTypeName,
  responseTypeName,
} from '../../utils/typeNames';

function quoteKeyIfNeeded(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : `'${key}'`;
}

export class TypeGenerator {
  createTypes(schemas: Record<string, SchemaModel>, operations: OperationModel[]): string {
    const lines: string[] = [];
    lines.push('// Generated by Swagger to SDK.');
    lines.push('');

    const schemaEntries = Object.entries(schemas);
    if (schemaEntries.length > 0) {
      for (const [schemaName, schema] of schemaEntries) {
        lines.push(this.generateSchemaDeclaration(schemaName, schema));
        lines.push('');
      }
    }

    for (const operation of operations) {
      const operationLines = this.generateOperationTypes(operation);
      if (operationLines.length > 0) {
        lines.push(...operationLines);
        lines.push('');
      }
    }

    return `${lines.join('\n').trim()}\n`;
  }

  private generateSchemaDeclaration(name: string, schema: SchemaModel): string {
    const typeName = toTypeName(name);
    const isObject = schema.type === 'object' || Boolean(schema.properties);

    if (isObject) {
      return `export interface ${typeName} ${this.renderObjectLiteral(schema)}`;
    }

    return `export type ${typeName} = ${this.schemaToType(schema)};`;
  }

  private generateOperationTypes(operation: OperationModel): string[] {
    const lines: string[] = [];

    const pathParameters = operation.parameters.filter((parameter) => parameter.in === 'path');
    if (pathParameters.length > 0) {
      lines.push(this.generateParameterInterface(pathParamsTypeName(operation.functionName), pathParameters));
    }

    const queryParameters = operation.parameters.filter((parameter) => parameter.in === 'query');
    if (queryParameters.length > 0) {
      lines.push(this.generateParameterInterface(queryParamsTypeName(operation.functionName), queryParameters));
    }

    const headerParameters = operation.parameters.filter((parameter) => parameter.in === 'header');
    if (headerParameters.length > 0) {
      lines.push(
        this.generateParameterInterface(headerParamsTypeName(operation.functionName), headerParameters)
      );
    }

    const cookieParameters = operation.parameters.filter((parameter) => parameter.in === 'cookie');
    if (cookieParameters.length > 0) {
      lines.push(
        this.generateParameterInterface(cookieParamsTypeName(operation.functionName), cookieParameters)
      );
    }

    const requestBodySchema = operation.requestBody?.content['application/json'];
    if (requestBodySchema) {
      lines.push(
        `export type ${requestBodyTypeName(operation.functionName)} = ${this.refOrInlineToType(
          requestBodySchema
        )};`
      );
    }

    const primaryStatus = pickPrimaryResponseStatus(operation.responses);
    if (primaryStatus) {
      const responseType = this.getResponseType(operation.responses, primaryStatus);
      lines.push(
        `export type ${responseTypeName(operation.functionName, primaryStatus)} = ${responseType};`
      );
    }

    lines.push(this.generateOperationArgsInterface(operation));

    return lines;
  }

  private generateParameterInterface(name: string, parameters: ParameterModel[]): string {
    const body = parameters
      .map((parameter) => {
        const typeValue = parameter.schema
          ? this.schemaToType(parameter.schema)
          : parameter.ref
            ? this.resolveRef(parameter.ref)
            : 'unknown';
        const optionalMark = parameter.required ? '' : '?';
        return `  ${quoteKeyIfNeeded(parameter.name)}${optionalMark}: ${typeValue};`;
      })
      .join('\n');

    return `export interface ${name} {\n${body}\n}`;
  }

  private generateOperationArgsInterface(operation: OperationModel): string {
    const fields: string[] = [];
    const hasPathParams = operation.parameters.some((parameter) => parameter.in === 'path');
    const hasQueryParams = operation.parameters.some((parameter) => parameter.in === 'query');
    const hasHeaderParams = operation.parameters.some((parameter) => parameter.in === 'header');
    const hasCookieParams = operation.parameters.some((parameter) => parameter.in === 'cookie');
    const hasBody = Boolean(operation.requestBody?.content['application/json']);
    const bodyRequired = operation.requestBody?.required === true;

    if (hasPathParams) {
      fields.push(`  path: ${pathParamsTypeName(operation.functionName)};`);
    }

    if (hasQueryParams) {
      fields.push(`  query?: ${queryParamsTypeName(operation.functionName)};`);
    }

    if (hasHeaderParams) {
      fields.push(`  headerParams?: ${headerParamsTypeName(operation.functionName)};`);
    }

    if (hasCookieParams) {
      fields.push(`  cookieParams?: ${cookieParamsTypeName(operation.functionName)};`);
    }

    if (hasBody) {
      fields.push(
        `  body${bodyRequired ? '' : '?'}: ${requestBodyTypeName(operation.functionName)};`
      );
    }

    fields.push('  headers?: Record<string, string>;');

    return `export interface ${operationArgsTypeName(operation.functionName)} {\n${fields.join('\n')}\n}`;
  }

  private getResponseType(responses: OperationResponseModel[], statusCode: string): string {
    if (statusCode === '204') {
      return 'void';
    }

    const response = responses.find((entry) => entry.statusCode === statusCode);
    if (!response) {
      return 'unknown';
    }

    const jsonContent = response.content['application/json'];
    if (!jsonContent) {
      return statusCode === '204' ? 'void' : 'unknown';
    }

    return this.refOrInlineToType(jsonContent);
  }

  private refOrInlineToType(schema: SchemaRefOrInline): string {
    if (schema.ref) {
      return this.resolveRef(schema.ref);
    }

    if (schema.schema) {
      return this.schemaToType(schema.schema);
    }

    return 'unknown';
  }

  private schemaToType(schema: SchemaModel): string {
    let baseType: string;

    if (schema.ref) {
      baseType = this.resolveRef(schema.ref);
    } else if (schema.enum && schema.enum.length > 0) {
      baseType = schema.enum.map((value) => JSON.stringify(value)).join(' | ');
    } else if (schema.type === 'array') {
      const itemType = schema.items ? this.refOrInlineToType(schema.items) : 'unknown';
      baseType = `(${itemType})[]`;
    } else if (schema.type === 'object' || schema.properties) {
      baseType = this.renderObjectLiteral(schema);
    } else {
      switch (schema.type) {
        case 'integer':
        case 'number':
          baseType = 'number';
          break;
        case 'boolean':
          baseType = 'boolean';
          break;
        case 'string':
          baseType = 'string';
          break;
        default:
          baseType = 'unknown';
          break;
      }
    }

    if (schema.nullable) {
      return `(${baseType}) | null`;
    }

    return baseType;
  }

  private renderObjectLiteral(schema: SchemaModel): string {
    const properties = schema.properties ?? {};
    const required = new Set(schema.required ?? []);

    const body = Object.entries(properties)
      .map(([propertyName, propertySchema]) => {
        const optionalMark = required.has(propertyName) ? '' : '?';
        return `  ${quoteKeyIfNeeded(propertyName)}${optionalMark}: ${this.refOrInlineToType(propertySchema)};`;
      })
      .join('\n');

    if (!body) {
      return '{ [key: string]: unknown; }';
    }

    return `{\n${body}\n}`;
  }

  private resolveRef(ref: string): string {
    const refName = ref.split('/').pop();
    if (!refName) {
      return 'unknown';
    }

    return toTypeName(refName);
  }
}
